//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace USDKDemo.RKIService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RKISoap", Namespace="http://tempuri.org/")]
    public partial class RKI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SecuredWebServiceHeader securedWebServiceHeaderValueField;
        
        private System.Threading.SendOrPostCallback ValidateDeviceOperationCompleted;
        
        private System.Threading.SendOrPostCallback PEDIOperationCompleted;
        
        private System.Threading.SendOrPostCallback PEDKOperationCompleted;
        
        private System.Threading.SendOrPostCallback PEDVOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeviceGroupListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RKI() {
            this.Url = global::USDKDemo.Properties.Settings.Default.UniversalSDKDemo_RKIService_RKI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SecuredWebServiceHeader SecuredWebServiceHeaderValue {
            get {
                return this.securedWebServiceHeaderValueField;
            }
            set {
                this.securedWebServiceHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidateDeviceCompletedEventHandler ValidateDeviceCompleted;
        
        /// <remarks/>
        public event PEDICompletedEventHandler PEDICompleted;
        
        /// <remarks/>
        public event PEDKCompletedEventHandler PEDKCompleted;
        
        /// <remarks/>
        public event PEDVCompletedEventHandler PEDVCompleted;
        
        /// <remarks/>
        public event DeviceGroupListCompletedEventHandler DeviceGroupListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecuredWebServiceHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateDevice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateDevice() {
            object[] results = this.Invoke("ValidateDevice", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateDeviceAsync() {
            this.ValidateDeviceAsync(null);
        }
        
        /// <remarks/>
        public void ValidateDeviceAsync(object userState) {
            if ((this.ValidateDeviceOperationCompleted == null)) {
                this.ValidateDeviceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateDeviceOperationCompleted);
            }
            this.InvokeAsync("ValidateDevice", new object[0], this.ValidateDeviceOperationCompleted, userState);
        }
        
        private void OnValidateDeviceOperationCompleted(object arg) {
            if ((this.ValidateDeviceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateDeviceCompleted(this, new ValidateDeviceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecuredWebServiceHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PEDI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PEDI(string _encryptioncert, string _signingCert, string _RG, string _RF, string _DG) {
            object[] results = this.Invoke("PEDI", new object[] {
                        _encryptioncert,
                        _signingCert,
                        _RG,
                        _RF,
                        _DG});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PEDIAsync(string _encryptioncert, string _signingCert, string _RG, string _RF, string _DG) {
            this.PEDIAsync(_encryptioncert, _signingCert, _RG, _RF, _DG, null);
        }
        
        /// <remarks/>
        public void PEDIAsync(string _encryptioncert, string _signingCert, string _RG, string _RF, string _DG, object userState) {
            if ((this.PEDIOperationCompleted == null)) {
                this.PEDIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPEDIOperationCompleted);
            }
            this.InvokeAsync("PEDI", new object[] {
                        _encryptioncert,
                        _signingCert,
                        _RG,
                        _RF,
                        _DG}, this.PEDIOperationCompleted, userState);
        }
        
        private void OnPEDIOperationCompleted(object arg) {
            if ((this.PEDICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PEDICompleted(this, new PEDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecuredWebServiceHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PEDK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PEDK(string _KN, string _KA, string _RD, string _AP, string _CE, string _FC) {
            object[] results = this.Invoke("PEDK", new object[] {
                        _KN,
                        _KA,
                        _RD,
                        _AP,
                        _CE,
                        _FC});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PEDKAsync(string _KN, string _KA, string _RD, string _AP, string _CE, string _FC) {
            this.PEDKAsync(_KN, _KA, _RD, _AP, _CE, _FC, null);
        }
        
        /// <remarks/>
        public void PEDKAsync(string _KN, string _KA, string _RD, string _AP, string _CE, string _FC, object userState) {
            if ((this.PEDKOperationCompleted == null)) {
                this.PEDKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPEDKOperationCompleted);
            }
            this.InvokeAsync("PEDK", new object[] {
                        _KN,
                        _KA,
                        _RD,
                        _AP,
                        _CE,
                        _FC}, this.PEDKOperationCompleted, userState);
        }
        
        private void OnPEDKOperationCompleted(object arg) {
            if ((this.PEDKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PEDKCompleted(this, new PEDKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecuredWebServiceHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PEDV", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PEDV(string _KV, string _KA, string _RD, string _AP, string _CE, string _FC) {
            object[] results = this.Invoke("PEDV", new object[] {
                        _KV,
                        _KA,
                        _RD,
                        _AP,
                        _CE,
                        _FC});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PEDVAsync(string _KV, string _KA, string _RD, string _AP, string _CE, string _FC) {
            this.PEDVAsync(_KV, _KA, _RD, _AP, _CE, _FC, null);
        }
        
        /// <remarks/>
        public void PEDVAsync(string _KV, string _KA, string _RD, string _AP, string _CE, string _FC, object userState) {
            if ((this.PEDVOperationCompleted == null)) {
                this.PEDVOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPEDVOperationCompleted);
            }
            this.InvokeAsync("PEDV", new object[] {
                        _KV,
                        _KA,
                        _RD,
                        _AP,
                        _CE,
                        _FC}, this.PEDVOperationCompleted, userState);
        }
        
        private void OnPEDVOperationCompleted(object arg) {
            if ((this.PEDVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PEDVCompleted(this, new PEDVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecuredWebServiceHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeviceGroupList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeviceGroupList(string _files) {
            object[] results = this.Invoke("DeviceGroupList", new object[] {
                        _files});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeviceGroupListAsync(string _files) {
            this.DeviceGroupListAsync(_files, null);
        }
        
        /// <remarks/>
        public void DeviceGroupListAsync(string _files, object userState) {
            if ((this.DeviceGroupListOperationCompleted == null)) {
                this.DeviceGroupListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeviceGroupListOperationCompleted);
            }
            this.InvokeAsync("DeviceGroupList", new object[] {
                        _files}, this.DeviceGroupListOperationCompleted, userState);
        }
        
        private void OnDeviceGroupListOperationCompleted(object arg) {
            if ((this.DeviceGroupListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeviceGroupListCompleted(this, new DeviceGroupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class SecuredWebServiceHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private string serialNumberField;
        
        private string productNameField;
        
        private string deviceGroupField;
        
        private string modelNumField;
        
        private string authenticatedTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public string DeviceGroup {
            get {
                return this.deviceGroupField;
            }
            set {
                this.deviceGroupField = value;
            }
        }
        
        /// <remarks/>
        public string ModelNum {
            get {
                return this.modelNumField;
            }
            set {
                this.modelNumField = value;
            }
        }
        
        /// <remarks/>
        public string AuthenticatedToken {
            get {
                return this.authenticatedTokenField;
            }
            set {
                this.authenticatedTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ValidateDeviceCompletedEventHandler(object sender, ValidateDeviceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateDeviceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateDeviceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PEDICompletedEventHandler(object sender, PEDICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PEDICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PEDICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PEDKCompletedEventHandler(object sender, PEDKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PEDKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PEDKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PEDVCompletedEventHandler(object sender, PEDVCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PEDVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PEDVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeviceGroupListCompletedEventHandler(object sender, DeviceGroupListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeviceGroupListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeviceGroupListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591